### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'Underpin_Scripts\Loaders\Scripts' not found in...

### ISSUE THREAD

**Issue by zamanq** [nicholas-wordpress/nearly-headless-theme#1]
Hi there,
I get this error when I try to activate the theme.
" Fatal error: Uncaught Error: Class 'Underpin_Scripts\Loaders\Scripts' not found in /Volumes/.../wp-content/themes/nearly-headless-theme/vendor/underpin/underpin/lib/factories/Loader_Registry.php on line 43"

Please note I've already ran composer install and npm install and then compiled using npm run start

**Comment by alexstandiford** [comment]
Hello @zamanq 

Can you tell me which version of Underpin you're running? It might help to run `composer update`.

**Comment by davemoz** [comment]
I'm getting this same error. I'm using the latest version of `nearly-headless-theme` which has `underpin/underpin: ^1.3`, `underpin/script-loader: ^1.1`, and `underpin/template-loader: ^1.0` in composer.lock. I also ran `composer update`, but still throwing the same error. Any ideas?

**Comment by alexstandiford** [comment]
This is super strange. I just ran `composer clearcache` and tried a fresh clone, and it worked without any trouble. The versions mentioned above match what I have.

I'm not sure why, but it appears that the [script loader](https://github.com/Underpin-WP/script-loader/blob/master/scripts.php) is not being required in-time.

The line in-question is:

```php
$this[ $key ]['registry'] = new $valid['registry']( $this->registry_id );
```

the issue is, in this context the `new $valid` instance is an instance of `Underpin_Scripts\Loaders\Scripts`, but the file isn't being found.

**Comment by rodmar35** [comment]
Hi,

First, thanks for this repo !
I meet same issue with Wordpress 5.8 when i active template.
Just for information, i'v got this error when i install it via composer.

`Failed to extract underpin/script-loader: (1) unzip -qq  'wp-content/themes/nearly-headless/vendor/composer/tmp-a34310b2853a75ec43a4f4258dc6df5b' -d 'wp-content/themes/nearly-headless/vendor/composer/80dc8fd3'`

`replace wp-content/themes/nearly-headless/vendor/composer/80dc8fd3/Underpin-WP-script-loader-5f21ad2/scripts.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)`

`the archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class`

I'm not sure this is where the problem is

I keep looking for a solution
thanks in advance
RodMar

**Comment by alexstandiford** [comment]
@rodmar35 - Okay I think that does help.

I would bet ten whole dollars that this is caused by the file structure in the script loader. In the current version there is both a `scripts.php` and a `Scripts.php` because I foolishly didn't build the directory structure for this appropriately. This works on my machine, (I'm running Ubuntu) and any system I've ever ran on because they have all ran on Linux, but I know some operating systems get tripped up by files with different file case like this.

I have opened an issue in the script loader to refactor the code to actually organize it appropriately. See: https://github.com/Underpin-WP/script-loader/issues/7

**Comment by alexstandiford** [comment]
@rodmar35 @davemoz @zamanq Can each of you try running `composer update` again? I updated the Underpin loaders that were flattened in a single directory and I think if you update it will fix this problem.

**Comment by zamanq** [comment]
@alexstandiford Indeed that was the issue. Running `composer update` fixed the issue. Thanks!

**Comment by alexstandiford** [comment]
Huzzah!

**Comment by rodmar35** [comment]
@alexstandiford : it's perfect, thanks a lot !
